#!/usr/bin/env -S uv run --script
"""Photo -> the map the robot localises against.

    python export_map.py [image] [--from i,j] [--theta0 deg|auto]
                         [-o ../firmware/micromouse/maze_map.h]

Runs exactly what ``maze_demo.py`` plans against -- ``maze_grid.solve`` for the
lattice, ``maze_map.build_map`` for the occupancy -- and emits the obstacle set
as a ``constexpr Map<N>`` for the firmware.  ``LidarObserver`` casts its three
beams into that map, so what comes out of here is the reference every pose fix
on the robot is measured against.

Everything ``build_map`` finds becomes an obstacle, because a lidar sees all of
it: panels as ``WallObstacle`` rectangles on their bonds, posts as
``CircularObstacle`` discs of the circumscribed radius, and free-standing
cylinders at their fitted footprint.  A post missing from the map is worse here
than it is for the planner -- the planner would merely drive into it, while the
observer gets a short reading it cannot explain, and ``impliedHeadingError``
throws the beam away.  The deck polygon is deliberately *not* an obstacle: it
is a drop-off, not a surface, and the beams that would cross it are the ones
already saturated at the sensor's 300 mm ceiling.

Frames
------
The maze map is image convention (+x east, +y south) and left-handed; the robot
is right-handed with +x forward and +y left.  This applies the same mirror and
re-origin as ``segments.to_firmware``, against the same start pose, so a map
exported here and a path exported by ``maze_demo.py`` land in one frame -- the
robot's odometry frame, with the start pose at (0, 0, 0).  Export both with the
same ``--from``/``--theta0`` or they will not agree.
"""

import argparse
import textwrap

import cv2
import numpy as np

import maze_grid as mg
import maze_map as mp
import rrt_star as rs

WALL_T_MM = mp.WALL_T_MM
POST_R_MM = mp.POST_R_MM


# ------------------------------------------------------------------- frames
def frame(start_mm, theta0):
    """Map mm -> robot mm, as ``(point fn, angle fn)``.

    Mirror the y axis, then rotate and translate so ``start_mm``/``theta0``
    sits at the origin facing +x.  Mirroring negates headings, which is why
    the rotation is by ``+theta0`` rather than ``-theta0``.
    """
    q = np.array([start_mm[0], -start_mm[1], -float(theta0)])
    c, s = np.cos(-q[2]), np.sin(-q[2])
    R = np.array([[c, -s], [s, c]])

    def point(p):
        p = np.atleast_2d(np.asarray(p, float)) * np.array([1.0, -1.0])
        return np.squeeze((p - q[:2]) @ R.T)

    def angle(a):
        return float(a) - q[2]

    return point, angle


# -------------------------------------------------------------------- emit
def obstacles(M, point, angle):
    """``(line, comment)`` pairs, in the firmware's frame."""
    out = []

    for seg in M["wall_segments_mm"]:
        a, b = point(seg[0]), point(seg[1])
        d = b - a
        centre = 0.5 * (a + b)
        # A panel's heading is a line, not a direction, so it is only defined
        # modulo pi; wrapping into [0, pi) keeps the mirror from emitting -pi
        # and +pi for what is the same wall.  WallObstacle picks the face the
        # sensor is on from the sign of the offset, so either would cast the
        # same -- this is for whoever reads the generated header.
        out.append(
            (
                f"Obstacle{{WallObstacle{{{np.linalg.norm(d):.2f}f, {WALL_T_MM:.2f}f, "
                f"{np.arctan2(d[1], d[0]) % np.pi:.5f}f}}, "
                f"Vec2D{{{centre[0]:.2f}f, {centre[1]:.2f}f}}}},",
                "panel",
            )
        )

    for c in M["post_centres_mm"]:
        p = point(c)
        out.append(
            (
                f"Obstacle{{CircularObstacle{{{POST_R_MM:.3f}f}}, "
                f"Vec2D{{{p[0]:.2f}f, {p[1]:.2f}f}}}},",
                "post",
            )
        )

    for c in M["cylinders"]:
        p = point(c["centre_mm"])
        out.append(
            (
                f"Obstacle{{CircularObstacle{{{c['radius_mm']:.2f}f}}, "
                f"Vec2D{{{p[0]:.2f}f, {p[1]:.2f}f}}}},",
                f"cylinder, r bound {c['radius_mm_bound']:.1f} mm, "
                f"fit rms {c['fit_rms_mm']:.1f} mm",
            )
        )

    del angle  # headings come out of the transformed endpoints
    return out


def header(rows, provenance):
    body = []
    last = None
    for line, comment in rows:
        group = comment.split(",")[0]
        if group != last:
            body.append(f"    // {group}s")
            last = group
        body.append(f"    {line}" + (f" // {comment}" if "," in comment else ""))

    return "\n".join(
        [
            "// Maze map",
            "//",
            "// GENERATED by path-planning/export_map.py -- do not edit by hand.",
            "//",
        ]
        + [f"// {line}" for line in provenance]
        + [
            "",
            "#pragma once",
            "",
            '#include "types.h"',
            "",
            "#pragma GCC push_options",
            '#pragma GCC optimize("Os")',
            "",
            f"constexpr size_t MAZE_OBSTACLE_COUNT = {len(rows)};",
            "",
            "// constexpr, so the whole map lives in flash and costs no RAM.",
            "constexpr Map<MAZE_OBSTACLE_COUNT> MAZE_MAP{{{",
        ]
        + body
        + [
            "}}};",
            "",
            "#pragma GCC pop_options",
            "",
        ]
    )


# --------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(
        description="emit the firmware's maze map from a photo",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """\
            The start pose must match the one maze_demo.py exported the path
            against, or the map and the path sit in different frames."""
        ),
    )
    ap.add_argument("image", nargs="?", default="mazes/1.png")
    ap.add_argument("--from", dest="src", default="0,1", help="start cell, i,j")
    ap.add_argument("--from-mm", dest="src_mm", default=None)
    ap.add_argument("--theta0", default="auto", help="start heading in deg, or 'auto'")
    ap.add_argument(
        "--r", type=float, default=40.0, help="robot radius, mm, for --theta0 auto"
    )
    ap.add_argument("-o", "--out", default="../firmware/micromouse/maze_map.h")
    a = ap.parse_args()

    img = cv2.imread(a.image)
    assert img is not None, a.image
    res = mg.solve(img)
    M = mp.build_map(img, res)
    W = M["frame"]

    if a.src_mm is not None:
        start = np.array([float(v) for v in a.src_mm.split(",")])
    else:
        i, j = (int(v) for v in a.src.split(","))
        start = W.cell_centre_mm(i, j)

    if a.theta0 == "auto":
        world = rs.MazeWorld(
            M["wall_segments_mm"],
            M["cylinders"],
            M["deck_mm"],
            robot_radius_mm=a.r,
            posts_mm=M["post_centres_mm"],
            post_radius_mm=M["post_radius_mm"],
        )
        theta0 = rs.best_heading(world, start)
    else:
        theta0 = np.radians(float(a.theta0))

    point, angle = frame(start, theta0)
    rows = obstacles(M, point, angle)

    n_panels = len(M["wall_segments_mm"])
    n_posts = len(M["post_centres_mm"])
    provenance = [
        f"{a.image}: {W.shape[0]}x{W.shape[1]} lattice, "
        f"{res['rms_px'] * res['mm_per_px']:.1f} mm fit rms",
        f"{n_panels} panels, {n_posts} posts "
        f"({len(M['isolated_posts'])} with no adjoining panel), "
        f"{len(M['cylinders'])} cylinders",
        "",
        "Robot frame: x forward, y left, mm. The origin is the start pose",
        f"{np.round(start, 1).tolist()} mm heading {np.degrees(theta0):.0f} deg in map"
        f" coordinates{' (auto)' if a.theta0 == 'auto' else ''}, which is where a",
        "freshly reset odometry frame reads (0, 0, 0). Export the path with the",
        "same --from/--theta0 or the two will not share a frame.",
    ]
    if M["walls"]["ambiguous"]:
        worst = M["walls"]["ambiguous"][0]
        provenance.append("")
        provenance.append(
            f"{len(M['walls']['ambiguous'])} bonds scored within 20 of the panel "
            f"threshold, worst {worst[0]}({worst[1]},{worst[2]}) at {worst[3]:.0f}."
        )
        provenance.append("Check those before trusting a fix taken against them.")

    text = header(rows, provenance)
    with open(a.out, "w") as f:
        f.write(text)

    print(
        f"{len(rows)} obstacles ({n_panels} panels, {n_posts} posts, "
        f"{len(M['cylinders'])} cylinders)"
    )
    print(
        f"start      {np.round(start, 1)} mm heading {np.degrees(theta0):.0f} deg"
        f"{' (auto)' if a.theta0 == 'auto' else ''}"
    )
    print(
        f"wrote      {a.out}  ({len(text) / 1024:.1f} KiB source, "
        f"~{len(rows) * 24 / 1024:.1f} KiB flash)"
    )


if __name__ == "__main__":
    main()
