"""Reading the generated headers back.

Most cases build their own header text, so the suite does not depend on
whichever maze happens to be installed in firmware/micromouse/ right now. The
two that do read the installed pair are marked, and skip when it is absent --
neither header is tracked by git, so a fresh checkout has neither.
"""

import math
import unittest

from ..maze_header import (
    MazeHeaderError,
    load_map,
    load_path,
    map_provenance,
    path_note,
    DEFAULT_MAP,
    DEFAULT_PATH,
)
from ..types import CircularObstacle, Segment, WallObstacle

MAP_HEADER = """\
// Maze map
//
// GENERATED by path-planning/export_map.py -- do not edit by hand.
//
// mazes/5.png: 10x10 lattice, 3.3 mm fit rms
// 2 panels, 1 posts (0 with no adjoining panel), 1 cylinders
//
// Robot frame: x forward, y left, mm. The origin is the start pose
// [270.0, 270.0] mm heading 90 deg in map coordinates (auto), which is where a
// freshly reset odometry frame reads (0, 0, 0).

#pragma once

constexpr size_t MAZE_OBSTACLE_COUNT = 4;

constexpr Map<MAZE_OBSTACLE_COUNT> MAZE_MAP{{{
    // panels
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{90.00f, 360.00f}},
    // posts
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, -90.00f}},
    // cylinders
    Obstacle{CircularObstacle{46.02f}, Vec2D{344.05f, 733.78f}}, // cylinder, r bound 58.7 mm
}}};
"""

PATH_HEADER = """\
// 3 segments, 500 mm -- 1,1 -> 4,6, r=30 mm
// Robot frame: x forward, y left, mm; path starts at the robot's pose.
planner.appendSegment(Segment({0.00f, 0.00f}, {100.00f, 0.00f}));
planner.appendSegment(Segment({100.00f, 0.00f}, {130.00f, 30.00f}, 1.0f / 30.00f, Segment::Direction::Left));
planner.appendSegment(Segment({130.00f, 30.00f}, {130.00f, -20.00f}, 1.0f / 25.00f, Segment::Direction::Right));
"""


def write(tmpdir, name, text):
    p = tmpdir / name
    p.write_text(text)
    return p


class TestLoadMap(unittest.TestCase):
    def setUp(self):
        import tempfile, pathlib

        self._tmp = tempfile.TemporaryDirectory()
        self.dir = pathlib.Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_parses_every_obstacle_in_file_order(self):
        """Order matters: an obstacle's index here is the index the firmware's
        Map has, which is what RayHit.index reports."""
        m = load_map(write(self.dir, "m.h", MAP_HEADER))
        self.assertEqual(len(m), 4)
        self.assertIsInstance(m[0].form, WallObstacle)
        self.assertIsInstance(m[1].form, WallObstacle)
        self.assertIsInstance(m[2].form, CircularObstacle)
        self.assertIsInstance(m[3].form, CircularObstacle)

    def test_reads_panel_geometry(self):
        w = load_map(write(self.dir, "m.h", MAP_HEADER))[0]
        self.assertAlmostEqual(w.form.length, 180.0)
        self.assertAlmostEqual(w.form.thickness, 12.0)
        self.assertAlmostEqual(w.form.alpha, math.pi / 2, places=4)
        self.assertAlmostEqual(w.centre.x, -270.0)
        self.assertAlmostEqual(w.centre.y, -180.0)

    def test_reads_circle_geometry(self):
        c = load_map(write(self.dir, "m.h", MAP_HEADER))[3]
        self.assertAlmostEqual(c.form.radius, 46.02)
        self.assertAlmostEqual(c.centre.x, 344.05)

    def test_a_truncated_header_is_rejected(self):
        """MAZE_OBSTACLE_COUNT disagreeing with what parsed is the failure
        build_maze.sh's temp-file dance exists to prevent."""
        cut = MAP_HEADER.replace("Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, -90.00f}},", "")
        with self.assertRaises(MazeHeaderError):
            load_map(write(self.dir, "m.h", cut))

    def test_the_count_check_can_be_waived(self):
        cut = MAP_HEADER.replace("Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, -90.00f}},", "")
        self.assertEqual(len(load_map(write(self.dir, "m.h", cut), strict=False)), 3)

    def test_an_empty_map_is_rejected(self):
        empty = "constexpr size_t MAZE_OBSTACLE_COUNT = 0;\n"
        with self.assertRaises(MazeHeaderError):
            load_map(write(self.dir, "m.h", empty))

    def test_a_missing_file_is_rejected(self):
        with self.assertRaises(MazeHeaderError):
            load_map(self.dir / "nope.h")

    def test_provenance(self):
        p = map_provenance(write(self.dir, "m.h", MAP_HEADER))
        self.assertEqual(p["image"], "mazes/5.png")
        self.assertEqual(p["lattice"], (10, 10))
        self.assertEqual(p["origin_mm"], (270.0, 270.0))
        self.assertEqual(p["origin_deg"], 90.0)

    def test_provenance_of_a_missing_file_is_empty(self):
        self.assertEqual(map_provenance(self.dir / "nope.h"), {})


class TestLoadPath(unittest.TestCase):
    def setUp(self):
        import tempfile, pathlib

        self._tmp = tempfile.TemporaryDirectory()
        self.dir = pathlib.Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_straights_and_arcs(self):
        segs = load_path(write(self.dir, "p.h", PATH_HEADER))
        self.assertEqual(len(segs), 3)
        self.assertEqual(segs[0].curvature, 0.0)
        self.assertAlmostEqual(segs[1].curvature, 1.0 / 30.0)
        self.assertAlmostEqual(segs[2].curvature, 1.0 / 25.0)

    def test_turn_direction(self):
        segs = load_path(write(self.dir, "p.h", PATH_HEADER))
        self.assertEqual(segs[1].direction, Segment.Direction.Left)
        self.assertEqual(segs[2].direction, Segment.Direction.Right)

    def test_endpoints_chain(self):
        segs = load_path(write(self.dir, "p.h", PATH_HEADER))
        for a, b in zip(segs, segs[1:]):
            self.assertAlmostEqual(a.end.x, b.start.x)
            self.assertAlmostEqual(a.end.y, b.start.y)

    def test_the_path_starts_at_the_odometry_origin(self):
        """maze_path.h carries its own start, which is why setup() needs no
        setStart() for it and a freshly reset frame is enough."""
        segs = load_path(write(self.dir, "p.h", PATH_HEADER))
        self.assertAlmostEqual(segs[0].start.x, 0.0)
        self.assertAlmostEqual(segs[0].start.y, 0.0)

    def test_a_path_with_no_segments_is_rejected(self):
        with self.assertRaises(MazeHeaderError):
            load_path(write(self.dir, "p.h", "// nothing here\n"))

    def test_note(self):
        n = path_note(write(self.dir, "p.h", PATH_HEADER))
        self.assertEqual(n, "3 segments, 500 mm -- 1,1 -> 4,6, r=30 mm")


class TestInstalledHeaders(unittest.TestCase):
    """The pair actually in firmware/micromouse/. Neither is tracked by git."""

    def test_installed_map_loads(self):
        if not DEFAULT_MAP.exists():
            self.skipTest("no maze_map.h installed -- run scripts/build_maze.sh")
        self.assertGreater(len(load_map()), 0)

    def test_installed_path_loads_and_is_drivable(self):
        if not DEFAULT_PATH.exists():
            self.skipTest("no maze_path.h installed -- run scripts/build_maze.sh")
        segs = load_path()
        self.assertGreater(len(segs), 0)
        # segments.check() enforces this on the way out; if it does not hold on
        # the way back in, the emitter and the parser disagree.
        for k, (a, b) in enumerate(zip(segs, segs[1:])):
            self.assertAlmostEqual(a.end.x, b.start.x, places=2, msg=f"gap at {k}")
            self.assertAlmostEqual(a.end.y, b.start.y, places=2, msg=f"gap at {k}")


if __name__ == "__main__":
    unittest.main()
