#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow>=11.0"]
# ///
"""Splash art -> the bitmap the OLED blits at bring-up.

    ./scripts/export_splash.py [image] [-o firmware/micromouse/splash_screen.h]

Reads a two-tone 128x64 PNG and emits it as a ``constexpr uint8_t[1024]`` in
the layout ``Adafruit_GFX::drawBitmap`` reads: row-major, 16 bytes per row, most
significant bit leftmost, a set bit meaning a lit pixel.  White in the source is
therefore ink, which is what the art already is -- a white logo on black -- so
nothing is inverted on the way through.

Unlike ``path-planning/export_map.py`` this carries its own dependency block and
imports nothing local, so ``uv run --script`` is enough and it does not need the
path-planning project's environment.  ``scripts/build.sh --flash`` runs it
before every compile it is going to upload, so the art on the panel is whatever
``hardware/Splashscreen.png`` last held.

The source must be exactly 128x64 and hold exactly two distinct values, and
both are hard errors rather than something to fix up here.  Rescaling or
thresholding art that does not already match the panel would put pixels on the
robot that the artist never saw, and at 128x64 with a 49x56 logo there is no
resampling that is not a visible change -- so a mismatch is a re-export from
Aseprite, not a decision for this script.
"""

import argparse
import sys
from pathlib import Path

from PIL import Image

WIDTH = 128
HEIGHT = 64
STRIDE = WIDTH // 8  # bytes per row


def load(path):
    """The source as a list of rows of 0/255, checked against the panel."""
    with Image.open(path) as im:
        grey = im.convert("L")

    if grey.size != (WIDTH, HEIGHT):
        raise SystemExit(
            f"{path}: {grey.size[0]}x{grey.size[1]}, but the panel is "
            f"{WIDTH}x{HEIGHT} -- re-export at the panel's size"
        )

    px = grey.tobytes()  # mode "L" is one byte per pixel, row-major
    values = set(px)
    if not values <= {0, 255}:
        extra = sorted(values - {0, 255})
        raise SystemExit(
            f"{path}: {len(extra)} grey value(s) between black and white "
            f"({extra[:8]}...) -- re-export with antialiasing off, since "
            f"the panel has no grey to render them with"
        )

    # Lists, not the bytes slices tobytes() would hand back: unpack() builds
    # lists, and the round-trip check in main() compares the two directly.
    return [list(px[y * WIDTH : (y + 1) * WIDTH]) for y in range(HEIGHT)]


def pack(rows):
    """Rows of 0/255 -> drawBitmap's bytes. White sets a bit."""
    out = bytearray()
    for row in rows:
        for base in range(0, WIDTH, 8):
            byte = 0
            for bit in range(8):
                if row[base + bit]:
                    byte |= 0x80 >> bit
            out.append(byte)
    return bytes(out)


def unpack(data):
    """pack() backwards, so the emitted bytes can be checked against the art."""
    return [
        [255 if data[y * STRIDE + (x >> 3)] & (0x80 >> (x & 7)) else 0 for x in range(WIDTH)]
        for y in range(HEIGHT)
    ]


def provenance(source, rows):
    """The lines describing where the art came from and what is in it.

    No timestamp: the header is committed, and a date would make every
    re-export a diff even when the art did not change.
    """
    lit = [(x, y) for y, row in enumerate(rows) for x, v in enumerate(row) if v]
    xs = [x for x, _ in lit]
    ys = [y for _, y in lit]
    box = (
        f"ink bounds x {min(xs)}..{max(xs)}, y {min(ys)}..{max(ys)}"
        if lit
        else "no lit pixels"
    )
    return [
        f"{source}: {WIDTH}x{HEIGHT}, {len(lit)} lit pixels of {WIDTH * HEIGHT}",
        box,
    ]


def header(data, lines):
    body = [
        "    " + ", ".join(f"0x{b:02X}" for b in data[y * STRIDE : (y + 1) * STRIDE]) + ","
        for y in range(HEIGHT)
    ]

    return "\n".join(
        [
            "// Splash screen bitmap",
            "//",
            "// GENERATED by scripts/export_splash.py -- do not edit by hand.",
            "//",
        ]
        + [f"// {line}" for line in lines]
        + [
            "//",
            "// One row of the panel per line, 16 bytes each: row-major, most",
            "// significant bit leftmost, a set bit lit. That is drawBitmap's own",
            "// layout, so oledSplash.h hands the array over without touching it.",
            "",
            "#pragma once",
            "",
            "#include <stdint.h>",
            "",
            f"constexpr uint8_t SPLASH_WIDTH  = {WIDTH};",
            f"constexpr uint8_t SPLASH_HEIGHT = {HEIGHT};",
            "",
            "// constexpr, so the bitmap lives in flash and costs no RAM.",
            f"constexpr uint8_t SPLASH_BITMAP[{len(data)}] = {{",
        ]
        + body
        + [
            "};",
            "",
        ]
    )


def main():
    ap = argparse.ArgumentParser(
        description="emit the firmware's splash bitmap from a two-tone PNG",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    root = Path(__file__).resolve().parent.parent
    ap.add_argument("image", nargs="?", default=str(root / "hardware/Splashscreen.png"))
    ap.add_argument("-o", "--out", default=str(root / "firmware/micromouse/splash_screen.h"))
    a = ap.parse_args()

    rows = load(a.image)
    data = pack(rows)

    # The one check worth having: a stride or bit-order slip survives every
    # other assertion here and only shows up as scrambled art after a flash.
    if unpack(data) != rows:
        raise SystemExit("packing did not round-trip -- refusing to write the header")

    source = Path(a.image).resolve()
    try:
        source = source.relative_to(root)
    except ValueError:
        pass

    text = header(data, provenance(str(source), rows))
    out = Path(a.out)

    # Only touch the file when the bytes change, so an unchanged re-export does
    # not restamp its mtime and send arduino-cli rebuilding on the next pass.
    if out.exists() and out.read_text() == text:
        print(f"{out.name} already current ({len(data)} bytes of bitmap)")
        return

    out.write_text(text)
    print(f"bitmap -> {out} ({len(data)} bytes, {WIDTH}x{HEIGHT})")


if __name__ == "__main__":
    sys.exit(main())
