// Maze map
//
// GENERATED by path-planning/export_map.py -- do not edit by hand.
//
// /Users/zimmylevi/Desktop/Uni/MTRN3100/Micromouse/path-planning/mazes/5.png: 10x10 lattice, 3.4 mm fit rms
// 79 panels, 54 posts (2 with no adjoining panel), 5 cylinders
// 
// Robot frame: x forward, y left, mm. The origin is the start pose
// [270.0, 270.0] mm heading 90 deg in map coordinates (auto), which is where a
// freshly reset odometry frame reads (0, 0, 0). Export the path with the
// same --from/--theta0 or the two will not share a frame.
// 
// 7 bonds scored within 20 of the panel threshold, worst vertical(0,9) at 63.
// Check those before trusting a fix taken against them.

#pragma once

#include "types.h"

#pragma GCC push_options
#pragma GCC optimize("Os")

constexpr size_t MAZE_OBSTACLE_COUNT = 138;

// constexpr, so the whole map lives in flash and costs no RAM.
constexpr Map<MAZE_OBSTACLE_COUNT> MAZE_MAP{{{
    // panels
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{90.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 0.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1170.00f, -0.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{630.00f, 180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 1080.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 1080.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{90.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{-180.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{900.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1260.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{0.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{360.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{1080.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{1260.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{-180.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{180.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{1260.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{0.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{900.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, 450.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 450.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, 630.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, 810.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, 810.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 810.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{-180.00f, 990.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, 990.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1260.00f, 990.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{0.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{540.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{-180.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{540.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{900.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1260.00f, 1350.00f}},
    // posts
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-270.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 1350.00f}},
    // cylinders
    Obstacle{CircularObstacle{48.32f}, Vec2D{610.94f, 978.91f}}, // cylinder, r bound 67.1 mm, fit rms 1.0 mm
    Obstacle{CircularObstacle{47.20f}, Vec2D{175.32f, 545.10f}}, // cylinder, r bound 60.3 mm, fit rms 1.4 mm
    Obstacle{CircularObstacle{45.98f}, Vec2D{356.94f, 756.59f}}, // cylinder, r bound 55.6 mm, fit rms 6.8 mm
    Obstacle{CircularObstacle{42.37f}, Vec2D{177.74f, 946.03f}}, // cylinder, r bound 58.2 mm, fit rms 10.3 mm
    Obstacle{CircularObstacle{38.47f}, Vec2D{559.88f, 457.78f}}, // cylinder, r bound 47.9 mm, fit rms 11.2 mm
}}};

#pragma GCC pop_options
