// Maze map
//
// GENERATED by path-planning/export_map.py -- do not edit by hand.
//
// /Users/zimmylevi/Desktop/Uni/MTRN3100/Micromouse/path-planning/mazes/5.png: 10x10 lattice, 3.3 mm fit rms
// 85 panels, 52 posts (2 with no adjoining panel), 5 cylinders
// 
// Robot frame: x forward, y left, mm. The origin is the start pose
// [270.0, 270.0] mm heading 90 deg in map coordinates, which is where a
// freshly reset odometry frame reads (0, 0, 0). Export the path with the
// same --from/--theta0 or the two will not share a frame.
// 
// 4 bonds scored within 20 of the panel threshold, worst horizontal(9,7) at 49.
// Check those before trusting a fix taken against them.

#pragma once

#include "types.h"

#pragma GCC push_options
#pragma GCC optimize("Os")

constexpr size_t MAZE_OBSTACLE_COUNT = 142;

// constexpr, so the whole map lives in flash and costs no RAM.
constexpr Map<MAZE_OBSTACLE_COUNT> MAZE_MAP{{{
    // panels
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{90.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1170.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, -180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 0.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1170.00f, -0.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{630.00f, 180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 180.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 360.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 540.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 720.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{630.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 900.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 1080.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{810.00f, 1080.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-270.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{-90.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{90.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{990.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1170.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 1.57080f}, Vec2D{1350.00f, 1260.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{-180.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{900.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1260.00f, -270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{0.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{360.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{1080.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{1260.00f, -90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{-180.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{180.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{1260.00f, 90.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{0.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{900.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 270.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{540.00f, 450.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 450.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, 630.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 3.14159f}, Vec2D{900.00f, 810.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 810.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{-180.00f, 990.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, 990.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1260.00f, 990.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{-180.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{0.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{540.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1260.00f, 1170.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{-180.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{180.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{360.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{540.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{720.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{900.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1080.00f, 1350.00f}},
    Obstacle{WallObstacle{180.00f, 12.00f, 0.00000f}, Vec2D{1260.00f, 1350.00f}},
    // posts
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, -90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 90.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-270.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 270.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 450.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 630.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 810.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{-90.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1350.00f, 990.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{90.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{270.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{450.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{630.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{810.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{990.00f, 1170.00f}},
    Obstacle{CircularObstacle{8.485f}, Vec2D{1170.00f, 1170.00f}},
    // cylinders
    Obstacle{CircularObstacle{46.02f}, Vec2D{344.05f, 733.78f}}, // cylinder, r bound 58.7 mm, fit rms 1.3 mm
    Obstacle{CircularObstacle{45.93f}, Vec2D{163.28f, 523.08f}}, // cylinder, r bound 58.7 mm, fit rms 1.3 mm
    Obstacle{CircularObstacle{46.03f}, Vec2D{167.04f, 921.75f}}, // cylinder, r bound 64.1 mm, fit rms 6.6 mm
    Obstacle{CircularObstacle{32.87f}, Vec2D{574.17f, 930.35f}}, // cylinder, r bound 65.3 mm, fit rms 5.3 mm
    Obstacle{CircularObstacle{24.64f}, Vec2D{541.75f, 412.36f}}, // cylinder, r bound 48.6 mm, fit rms 6.9 mm
}}};

#pragma GCC pop_options
