// Tasks 4.1 and 4.2 -- drive a pre-computed route
//
// Zimmy Levi z5587840
//
// Selected by TASK in micromouse.ino, which includes this file part way down
// the sketch rather than up with the other includes: everything here is built
// from lidar, obs_v, dt and display, so it has to come after them. The sketch
// is one translation unit, so those names are already in scope and this header
// declares no hardware of its own.
//
// Its counterpart is task43.h. Both declare the same names -- lidar_obsv,
// obs_p, sf, fusedPose(), and the three task hooks below -- so setup() and
// loop() are written once and neither is wrapped in an #if.
//
// The maze is known ahead of time here: maze_map.h is fitted by CV from a
// photograph of it, and maze_path.h is the route through it, both generated by
// scripts/build_maze.sh. The observer localises against that map and
// MotionPlanner drives that route as blended arcs. Its std::array<Segment,
// PATH_SEGMENTS_MAX_LEN> is about 10 kB of the sketch's RAM, which is why this
// and task43.h are alternatives rather than both being built.

#pragma once

#include <array>

#include <Embedded_Template_Library.h>
#include <etl/delegate.h>

#include "constants.h"
#include "maze_map.h"
#include "observers.h"
#include "oledScreen.h"
#include "planners.h"
#include "sensorFusion.h"
#include "types.h"

LidarObserver<Map<MAZE_OBSTACLE_COUNT>> lidar_obsv(lidar, MAZE_MAP);

// The lidar for position, the gyro for heading, and neither for the other.
//
// XYPTrust on the lidar for the reason set out over LidarObserver: three beams
// in a corridor constrain y and theta only in combination, so a lateral offset
// comes back partly as rotation, and that heading is worse than the gyro's.
//
// ThetaPTrust on the IMU because heading is all it has -- the x and y in the
// Pose it returns are placeholders. This is the axis that had no absolute
// reference at all before: theta was dead reckoning from the fused omega, with
// nothing on the pose side weighted to correct it, so every error in that omega
// integrated for the whole run with nothing to pull it back.
const std::array<PoseSource, 2> obs_p = {{
    {&lidar_obsv, FusionWeights::XYPTrust},
    {&imu_obsv, FusionWeights::ThetaPTrust}
}};

SensorFusion sf(obs_v, obs_p, 0.1f, FusionWeights::ThetaCorrectionGain);

Pose fusedPose() { return sf.estimate.pose(); }

MotionPlanner planner(10, 0.06f);

// Delegate, so the display does not depend on the planner's type. The
// equivalent of MazeRunner::raceProgress() on this side.
float routeProgress() {
    return planner.progress(sf.estimate.pose());
}

// Fixed, because this task has exactly one phase. The maze arrived as a
// photograph and the route was computed from it offline, so there is nothing to
// explore and nothing to decide: the robot drives the route it was given from
// the moment it starts. "CV" names where the map came from, which is the only
// thing distinguishing this run from 4.3's final lap.
const char* screenMode() {
    return "CV";
}

// Distance along the route, from MotionPlanner's own arc-length measure rather
// than from a step count -- the route here is blended arcs, not poses, so there
// are no steps to count.
OLEDMetric screenMetric() {
    return OLEDMetric{'P', routeProgress()};
}

// The exported map, drawn as geometry: 85 panels as lines at their own angles,
// 52 posts and 5 cylinders as filled discs. Everything reaches it through a
// delegate, so nothing here couples the screen to MotionPlanner.
//
// No route overlay. maze_path.h is fed straight to the planner as segments, so
// there is no polyline to hand over -- and the map the route was cut through is
// on screen either way.
OLEDScreen<Map<MAZE_OBSTACLE_COUNT>> screen(
    display,
    MAZE_MAP,
    etl::delegate<Pose()>::create<fusedPose>(),
    etl::delegate<const char*()>::create<screenMode>(),
    etl::delegate<OLEDMetric()>::create<screenMetric>()
);

// Called from setup(), after the shared bring-up and under its "Loading
// goal..." print, which this is expected to terminate.
void taskBegin() {
    // Loads the pre-computed route. maze_path.h is a bare list of
    // planner.appendSegment(...) calls, so it is included here, inside a
    // function body, rather than at file scope.
#include "maze_path.h"

    if (planner.s() != MotionPlanner::State::Run) {
        Serial.println("\b\b\b [maze_path.h APPENDED NO SEGMENTS]");
    } else {
        Serial.println("\b\b\b [OKAY]");
    }

    // The map is fixed, so one fit in setup() holds for the whole run.
    Serial.print("Fitting map to display...");
    if (!screen.init()) {
        Serial.println("\b\b\b [MAP DID NOT FIT]");
    } else {
        Serial.println("\b\b\b [OKAY]");
    }
}

Velocity taskUpdate(const Pose& pose, float dt) {
    return planner.update(pose, dt);
}

// The OLED_REFRESH_MS gate that used to wrap this -- and a previous_oled_time
// to go with it -- is gone from loop(): it duplicated the one inside the
// renderer, and both now live in OLEDDisplay::due().
void taskRender() {
    screen.update();
}
