// Tasks 4.1 and 4.2 -- drive a pre-computed route
//
// Zimmy Levi z5587840
//
// Selected by TASK in micromouse.ino, which includes this file part way down
// the sketch rather than up with the other includes: everything here is built
// from lidar, obs_v, dt and display, so it has to come after them. The sketch
// is one translation unit, so those names are already in scope and this header
// declares no hardware of its own.
//
// Its counterpart is task43.h. Both declare the same names -- lidar_obsv,
// obs_p, sf, fusedPose(), and the three task hooks below -- so setup() and
// loop() are written once and neither is wrapped in an #if.
//
// The maze is known ahead of time here: maze_map.h is fitted by CV from a
// photograph of it, and maze_path.h is the route through it, both generated by
// scripts/build_maze.sh. The observer localises against that map and
// MotionPlanner drives that route as blended arcs. Its std::array<Segment,
// PATH_SEGMENTS_MAX_LEN> is about 10 kB of the sketch's RAM, which is why this
// and task43.h are alternatives rather than both being built.

#pragma once

#include <array>

#include <Embedded_Template_Library.h>
#include <etl/delegate.h>

#include "constants.h"
#include "maze_map.h"
#include "observers.h"
#include "oled.h"
#include "oledPath.h"
#include "planners.h"
#include "sensorFusion.h"
#include "types.h"

LidarObserver<Map<MAZE_OBSTACLE_COUNT>> lidar_obsv(lidar, MAZE_MAP);

const std::array<PoseSource, 1> obs_p = {{
    {&lidar_obsv, FusionWeights::XYPTrust}
}};

SensorFusion sf(obs_v, obs_p, 0.1);

Pose fusedPose() { return sf.estimate.pose(); }

MotionPlanner planner(10, 0.06f, 200.0f);

// Delegate, so the display does not depend on the planner's type. The
// equivalent of MazeRunner::raceProgress() on this side.
float routeProgress() {
    return planner.progress(sf.estimate.pose());
}

// The exported map is what OLEDPath was written for. Kept constructed and
// available for bring-up, but not driven by taskRender(): OLEDDisplay::due()
// is consuming, so only one renderer may draw per tick.
OLEDPath<Map<MAZE_OBSTACLE_COUNT>> oledPath(
    display,
    MAZE_MAP,
    etl::delegate<Pose()>::create<fusedPose>(),
    etl::delegate<float()>::create<routeProgress>()
);

// The scalar readout, which is what this task actually draws.
const std::array values = {
    OLEDValue{"x", []() { return sf.estimate.pose().x; }},
    OLEDValue{"y", []() { return sf.estimate.pose().y; }},
    OLEDValue{"th", []() { return sf.estimate.pose().theta; }},
    OLEDValue{"dt", []() { return dt; }},
    OLEDValue{"pgr", []() { return routeProgress(); }},
    OLEDValue{"sta",
              []() {
                return static_cast<float>(static_cast<uint8_t>(planner.s()));
              }},
    OLEDValue{"idx", []() { return static_cast<float>(planner.idx()); }},
};

OLEDValues oled(display, values);

// Called from setup(), after the shared bring-up and under its "Loading
// goal..." print, which this is expected to terminate.
void taskBegin() {
    // Loads the pre-computed route. maze_path.h is a bare list of
    // planner.appendSegment(...) calls, so it is included here, inside a
    // function body, rather than at file scope.
#include "maze_path.h"

    if (planner.s() != MotionPlanner::State::Run) {
        Serial.println("\b\b\b [maze_path.h APPENDED NO SEGMENTS]");
    } else {
        Serial.println("\b\b\b [OKAY]");
    }

    // The map is fixed, so one fit in setup() holds for the whole run.
    Serial.print("Fitting map to display...");
    if (!oledPath.init()) {
        Serial.println("\b\b\b [MAP DID NOT FIT]");
    } else {
        Serial.println("\b\b\b [OKAY]");
    }
}

Velocity taskUpdate(const Pose& pose, float dt) {
    return planner.update(pose, dt);
}

// The OLED_REFRESH_MS gate that used to wrap this -- and a previous_oled_time
// to go with it -- is gone from loop(): it duplicated the one inside the
// renderer, and both now live in OLEDDisplay::due().
void taskRender() {
    oled.update();
}
